### ISSUE TITLE
Add a hook for after successful test

### ISSUE THREAD

**Issue by martndemus** [kategengler/ember-try#15]
It would be cool to hook into ember-try, for example to push the resulting build with ember-cli-deploy so a manual E2E test can be done.

So this hook should run after the build passes the tests, but before bower is reset. And optionally with an option to run even when the tests fail?

**Comment by kategengler** [comment]
I think this is out of the scope of this addon. 
You can achieve this by creating another addon with a command that does that. 

`ember try ember-canary test-and-deploy` ... where `ember test-and-deploy` is the command that will deploy if the tests pass, or fail, as you please.
