### ISSUE TITLE
Killing ember-try while it's running leaves bower.json modified

### ISSUE THREAD

**Issue by truenorth** [kategengler/ember-try#20]
### Scenario
I have a hanging test, and I kill ember-try with `ctrl-c`. My bower.json is left in a state where my scenario is still applied

### Suggestions

1. We find a way to have ember-try clean up after its self upon teardown
2. We add a command to ember-try, to easily restore the project's original bower.json

**Comment by rwjblue** [comment]
I think I prefer option 2, and try to detect the scenario (by seeing the old backup/lock file and restoring first).

**Comment by truenorth** [comment]
After talking with @stefanpenner it sounds like any solution similar to option 1 would be difficult to accomplish in a robust and predictable way.

Another idea is to restore bower.json before the tests actually start running (i.e., immediately after `bower install` completes) but I'm not sure if there are any negative ramifications with this approach.

**Comment by kategengler** [comment]
So for option 2, something like this? https://github.com/kategengler/ember-try#ember-tryreset

**Comment by rwjblue** [comment]
Hehe, yep!
