### ISSUE TITLE
Allow testing of `beta` and `canary` versions.

### ISSUE THREAD

**Issue by rwjblue** [kategengler/ember-try#3]
I would like the following configuration to work:

```javascript
module.exports = {
  scenarios: [
    {
      name: 'ember-release',
      dependencies: {
        "ember": "components/ember#release"
      }
    },
    {
      name: 'ember-beta',
      dependencies: {
        "ember": "components/ember#beta"
      }
    },
    {
      name: 'ember-canary',
      dependencies: {
        "ember": "components/ember#canary"
      }
    }
  ]
};
```

Currently this throws an error in [lib/utils/scenario-manager.js#L32](https://github.com/kategengler/ember-try/blob/8b45dfc1e09361559aa822d8c61bba8340aad89f/lib/utils/scenario-manager.js#L32) because the version actually contains the SHA:

```
Error: Versions do not match: 1.13.0-beta.1+canary.8e8b3326 expected: components/ember#canary
```

----

Thoughts on allowing this warning to be opted out of in the case that the version specified in `dependencies` is not a valid "SemVer" version number?

**Comment by rwjblue** [comment]
In the above scenario removing the line that throws the error does allow this to work properly, though an additional bower prompt asking for resolution is displayed.

**Comment by kategengler** [comment]
I just committed a fix for this before even seeing this issue, nice :)

**Comment by kategengler** [comment]
Not quite there yet. Works with "canary" but not with "components/ember#canary". I need to look a bit more into how resolutions are done in bower.
