### ISSUE TITLE
Removing ember-data causes error

### ISSUE THREAD

**Issue by thoov** [kategengler/ember-try#35]
Steps to reproduce:

- `ember addon foo`
- Remove ember-data from bower.json
- `rm -rf bower_components; bower i`
- `ember try default test`

And you will get this error:
<img width="972" alt="screen shot 2015-07-17 at 12 25 53 pm" src="https://cloud.githubusercontent.com/assets/166909/8755349/03801d54-2c7f-11e5-9aa9-6f9b534ddc5c.png">

**Comment by truenorth** [comment]
Not really an ember-try issue. You probably didn't remove the ember-data node.js devDependency.

https://github.com/ember-cli/ember-cli/blob/b898e4e033130b4266c31dec4df77b3e0716a7f1/blueprints/app/files/package.json#L35

Path for successfully doing what you're trying to do:

```shell
ember addon foo --skip-bower --skip-npm
cd foo
# Remove ember-data from both package.json and bower.json
npm i; bower i
ember try default test
```

**Comment by thoov** [comment]
Good catch
