### ISSUE TITLE
Add a parameter to the scenarios to warn on failure instead of fail

### ISSUE THREAD

**Issue by habdelra** [kategengler/ember-try#4]
I think a useful idea would be to add a parameter to the scenarios where for a particular scenario you would warn if there was a failure instead of actually failing. This way the travis build doesn't fail if the project relies on a release ember version, when the canary ember version causes a test failure.

**Comment by kategengler** [comment]
:+1:

**Comment by rwjblue** [comment]
Like Travis's [allow_failures](http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail) option?

**Comment by kategengler** [comment]
Yeah, I think so. I looked into this a bit last night. I think it only makes sense for the `testall` command, not the individual `try` commands, because that can be done with any command, not just tests.

**Comment by martndemus** [comment]
This works for me on codeship using individual builds.
```
ember try ember-stable && ember try ember-beta && (ember try ember-canary || exit 0)
```

**Comment by jrjohnson** [comment]
We're using travis's allow failures and the build matrix based on environmental variables to handle this:
https://github.com/ilios/frontend/blob/master/.travis.yml
