### ISSUE TITLE
What is the most convenient way to execute ember-try builds concurrently on Linux?

### ISSUE THREAD

**Issue by mkorfmann** [kategengler/ember-try#40]

**Comment by mike-north** [comment]
The way ember-try works is not conducive to scenarios being run in parallel (the bower.json is modified, dependencies are satisfied, tests are run, etc...).

You would have to create an independent working copy for each scenario you'd want to test or something (see: travis-ci's "build matrix" for an practical example).

**Comment by mkorfmann** [comment]
Ok, thanks for taking the time to explain! :)
