### ISSUE TITLE
ember try:testall should honor all or a subset of 'ember test' arguments

### ISSUE THREAD

**Issue by enrico** [kategengler/ember-try#43]
```
ember try:testall --test-port $MY_TEST_PORT

The option '--test-port' is not registered with the try:testall command. Run `ember try:testall --help` for a list of supported options.
```

Background: we run multiple concurrent project tests on the same build machine, and our build system chooses a port and exposes it as an environment variable.

**Comment by rwjblue** [comment]
@enrico - It does generally work, but that warning is triggered by ember-cli itself due to some bizarre internals (it isn't really expecting commands to emulate other commands with dynamic options). 

I'll continue to think of a way to prevent that warning in the `ember try` case, but still provide helpful feedback if you accidentally supply an invalid option to another command (i.e. `ember test --test-prot=5678`).

**Comment by kategengler** [comment]
I don't think the options are passed along in the `try:testall` command. My thoughts here are to replace `try:testall` with a `try:each` command that you pass a command to:

`ember try:each --some-ember-try-option=blah -- ember test --test-port=3001 --config-file='./testem-{{scenario-name}}.json'`

Where the command to run for each scenario is after the ' -- '; probably with a default of `ember test` like now, and maybe a default command that can be set in config. {{scenario-name}} would be replaced by `ember-try` with the name.

**Comment by rwjblue** [comment]
> I don't think the options are passed along in the try:testall command. 

Ahh, gotcha. I had forgotten this.

> My thoughts here are to replace try:testall with a try:each command 

Yeah, that seems good.

We still need to fix the issue I mentioned in ember-cli though...

**Comment by enrico** [comment]
@kategengler : are you already working on this ? If not, I can try to take a stab at it...

**Comment by kategengler** [comment]
@enrico Yes I am, thanks for the offer, though!

**Comment by kategengler** [comment]
https://github.com/kategengler/ember-try/pull/59 provides configurable commands. Since `ember-try` config is a javascript file, you should be able to reference your ENV var in there.

**Comment by dexturr** [comment]
> My thoughts here are to replace try:testall with a try:each command that you pass a command to:
> ember try:each --some-ember-try-option=blah -- ember test --test-port=3001 --config-file='./testem-{{scenario-name}}.json'

Is this now working? Not sure if this is a bug here or with ember-cli, but creating a new addon in ember-cli 2.18.2 and trying to run: 

```ember try:each -- ember test --test-port=3001``` 

always uses the default port, 7357. This is causing our build server to error if that port is in use.

**Comment by rwjblue** [comment]
You need three dashes to separate (your example only used two)

**Comment by dexturr** [comment]
Tried with three dashes, with the same result:
`ember try:each --- ember test --test-port=3001`,
as I am running something else on 7357 I get the following error `listen EADDRINUSE :::7357`

**Comment by kategengler** [comment]
Only `ember try:one` takes a command via the command line like that. For `ember try:each` the only current way to customize the command is to put it in the config https://github.com/ember-cli/ember-try#configuration-files By default, this is `config/ember-try.js` but both commands take an optional `--config-path` https://github.com/ember-cli/ember-try#ember-tryeach

**Comment by dexturr** [comment]
Ah ok, I understand thank you very much for your help. 

Are there any plans to introduce functionality at a later date? Currently our build server provides the ports which we pass to apps through command line, so using configuration files might be difficult as we cannot guarantee which ports will be free and which will be in use. 

If someone would point me in the general direction I would be happy to take a run at this myself.

**Comment by kategengler** [comment]
@dexturr Your config file can have javascript in it, so you could have:

```js
module.exports = function() {
  return {
    command:  `ember test --test-port=${process.env.BUILD_PORT}`,
    scenarios: [
     // scenarios here
    ]
  }
}
```

**Comment by dexturr** [comment]
Perfect, thank you so much for all your help!
