### ISSUE TITLE
[enhancement] Handle ember and ember data as addons

### ISSUE THREAD

**Issue by jnfingerle** [kategengler/ember-try#44]
Ember data 2.3 will be an ember-cli addon and ember will follow. Supporting dependencies in package.json as well as in bower.json would help handling this new development.

As before, I could try to get my hands dirty, but I'm not aware if there's already anything done in that direction.

**Comment by fsmanuel** [comment]
:+1:

**Comment by rwjblue** [comment]
0.1.0 allows customization of both npm and bower deps.

You can use configuration like:

```
    {
      name: 'ember-data-2.3',
      bower: {
        dependencies: {
          "ember": "release"
        },
        devDependencies: {
          "ember-cli-shims": "ember-cli/ember-cli-shims#0.1.0"
        },
        resolutions: {
          "ember": "release"
        }
      },
      npm: {
        devDependencies: {
          "ember-data": "~2.3"
        }
      }
    }
```

**Comment by rwjblue** [comment]
Closing this for now, happy to reopen if needed.
