### ISSUE TITLE
Running an individual scenario with `ember try` returns a nonzero exit code when all tests pass

### ISSUE THREAD

**Issue by habdelra** [kategengler/ember-try#5]
So I saw that when you run an individual scenario with `ember try foo`, and the tests all pass, a non-zero exit code will still be returned, causing travis to fail the test. (However, `ember try:testall` exits with a `0` code when all the tests pass).

**Comment by kategengler** [comment]
I just noticed this today too. Definitely needs some investigation.

**Comment by habdelra** [comment]
For the time being I'm using this little shell script to run my mulitple scenarios:

```sh
echo "Running ember try for channel: ${EMBER_CHANNEL}"
cp -f "./config/ember-try-${EMBER_CHANNEL}.js" ./config/ember-try.js
ember try:testall
exit_code=$?
rm ./config/ember-try.js
exit ${exit_code}
```

where I have an `ember-try-release.js`, `ember-try-beta.js` and an `ember-try-canary.js` file, with just one scenario each.
