### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by rwjblue** [kategengler/ember-try#7]
A few bugs have been fixed, and I'd love a new version published to take advantage of them.

Also, I'd like to get this integrated into Ember CLI's default addon setup, and we can't rely on a git SHA (due to non-git users).

**Comment by kategengler** [comment]
It's been less than 24 hours since those bugs were fixed. My plan are to fix the other outstanding issue tonight and then release a new version.

It'd be nice to have it in the default setup.

**Comment by rwjblue** [comment]
Sorry, didn't mean to infer that this is stagnate. I'm just chomping at the bit :smile:

**Comment by rwjblue** [comment]
Also, I worked on the ember-cli integration this morning. Ran into a few issues, and am trying to work up a PR here to clear the way for that....

**Comment by kategengler** [comment]
No problem. If there's anything related to the ember-cli integration I can work on, let me know.

**Comment by kategengler** [comment]
Released 0.0.3
